name: vertical_farming
description: A new Flutter project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^3.3.1
  fl_chart: ^1.0.0
  flutter_riverpod: ^2.6.1
  curved_navigation_bar: ^1.0.6
  vertical_card_pager: ^1.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
