// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
///
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNlsqcXsJu_VROe249h2KqwMYO_gMZ28k',
    appId: '1:925298690499:android:c628c78b1dab6191471576',
    messagingSenderId: '925298690499',
    projectId: 'vertical-farming-13e73',
    databaseURL: 'https://vertical-farming-13e73-default-rtdb.firebaseio.com',
    storageBucket: 'vertical-farming-13e73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1nZ3WQW9sMU_GUa7u-XFGuyY-Pa-PeSY',
    appId: '1:925298690499:ios:e1bf4ed98f15e749471576',
    messagingSenderId: '925298690499',
    projectId: 'vertical-farming-13e73',
    databaseURL: 'https://vertical-farming-13e73-default-rtdb.firebaseio.com',
    storageBucket: 'vertical-farming-13e73.firebasestorage.app',
    iosBundleId: 'com.example.verticalFarming',
  );
}